name: Deployment test
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Echo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Output the input value
        run: |
          echo "The pipeline ran successfully."
